# P A C K A G E : : : C O M P A R I S O N

In [1]:
import pandas as pd
import numpy as np
import matplotlib as m
import matplotlib.pyplot as plt

In [2]:
# if you want to run this, you need to run do_DGE.ipynb and get all results in DGE_results

# 42/44

In [3]:
RALL_bayexpress = pd.read_csv('DGE_results/RALL_bayexpress.csv').iloc[:,1:].rename(columns={'genes': "locus_name"})

# we don't loose any genes here for nans
# RALL_bayexpress = RALL_bayexpress.dropna(subset=['BF_21', 'FC'])

# criteria 1 for significance: (BF_21 > 1) & (abs(FC) > 1)
RALL_bayexpress['FC1_bayexpress'] = (RALL_bayexpress.BF_21 > 1) & (abs(RALL_bayexpress.FC) > 1)

RALL_bayexpress

     locus_name      BF_21        FC  FC1_bayexpress
0      15S_rRNA  -3.710645  0.274047           False
1      21S_rRNA  -1.302642  0.147177           False
2          HRA1  -5.206545 -0.564787           False
3          ICR1  76.746125  0.504048           False
4          LSR1   0.451012  0.120243           False
...         ...        ...       ...             ...
7121  tY(GUA)J2  -7.312143  0.861839           False
7122  tY(GUA)M1  -7.406574  0.022303           False
7123  tY(GUA)M2  -7.727890  0.183767           False
7124   tY(GUA)O  -7.622253  0.347266           False
7125   tY(GUA)Q  -8.273720 -0.138161           False

[7126 rows x 4 columns]

In [4]:
RALL_edgeR = pd.read_csv('DGE_results/RALL_edgeR.csv').rename(columns={'genes': "locus_name"})

# we don't loose any genes here for nans
# RALL_edgeR = RALL_edgeR.dropna(subset=['logFC', 'PValue'])

# however, we do have already lost some during their analysis


# criteria 1 for significance: (pvalue < 0.05) & (abs(log2FoldChange) > 1)
RALL_edgeR['FC1_edgeR'] = (RALL_edgeR.PValue < 0.05) & (abs(RALL_edgeR.logFC) > 1)

RALL_edgeR

,locus_name,logFC,logCPM,F,PValue,FDR,FC1_edgeR
0,YIL121W,-2.833997,6.681355,1.393437e+04,2.275960e-99,1.386970e-95,True
1,YDR033W,-3.765504,8.923851,1.149128e+04,1.110106e-95,3.382494e-92,True
2,YML123C,-4.669706,9.152594,1.051245e+04,5.593728e-94,1.136273e-90,True
3,YGR234W,-4.212037,8.462599,9.288989e+03,1.292927e-91,1.969774e-88,True
4,YOR290C,-7.557956,6.530807,9.462461e+03,1.696224e-91,2.067358e-88,True
...,...,...,...,...,...,...,...
6089,YBL052C,0.000363,5.364961,4.246443e-05,9.948153e-01,9.954687e-01,False
6090,YHR117W,0.000097,6.355627,2.441982e-05,9.960682e-01,9.965588e-01,False
6091,YMR123W,-0.000171,6.143127,2.150691e-05,9.963102e-01,9.966373e-01,False
6092,YGR136W,0.000152,6.616432,1.272198e-05,9.971621e-01,9.973258e-01,False
6093,YJL035C,-0.000037,5.440098,3.924203e-07,9.995016e-01,9.995016e-01,False

In [5]:
RALL_DESeq2 = pd.read_csv('DGE_results/RALL_DESeq2.csv').rename(columns={'Unnamed: 0': "locus_name"})

# this is a bit crazy but we loose a lot of genes for nans here
RALL_DESeq2 = RALL_DESeq2.dropna(subset=['log2FoldChange', 'pvalue'])

# criteria 1 for significance: (pvalue < 0.05) & (abs(log2FoldChange) > 1)
RALL_DESeq2['FC1_DESeq2'] = (RALL_DESeq2.pvalue < 0.05) & (abs(RALL_DESeq2.log2FoldChange) > 1)

RALL_DESeq2

,locus_name,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,FC1_DESeq2
0,15S_rRNA,16.994794,-0.136618,0.340703,-0.400988,6.884290e-01,7.313923e-01,False
1,21S_rRNA,102.643528,-0.243675,0.289561,-0.841533,4.000494e-01,4.548869e-01,False
2,HRA1,2.550649,-0.851126,0.230477,-3.692895,2.217160e-04,3.651076e-04,False
3,ICR1,142.961822,0.229845,0.034777,6.609078,3.867198e-11,9.556948e-11,False
4,LSR1,196.640749,-0.214104,0.162418,-1.318227,1.874278e-01,2.269904e-01,False
...,...,...,...,...,...,...,...,...
7120,tY(GUA)J1,0.140228,-0.042322,1.074228,-0.039397,9.685735e-01,9.738411e-01,False
7121,tY(GUA)J2,0.133175,-0.042322,1.000548,-0.042298,9.662608e-01,9.724756e-01,False
7122,tY(GUA)M1,0.385050,-0.273708,0.488968,-0.559768,5.756379e-01,6.256143e-01,False
7123,tY(GUA)M2,0.080417,-0.301508,1.426535,-0.211357,8.326090e-01,8.622913e-01,False
7124,tY(GUA)O,0.113977,-0.239053,1.167479,-0.204760,8.377597e-01,8.664623e-01,False

In [6]:
RALL = pd.DataFrame({'locus_name': RALL_bayexpress.locus_name})

# RALL = pd.concat([RALL, RALL_bayexpress.iloc[:,-2:], RALL_edgeR.iloc[:,-2:], RALL_DESeq2.iloc[:,-2:]], axis=1)

RALL = RALL.merge(RALL_bayexpress[['locus_name', 'FC1_bayexpress']], on='locus_name', how='left')

# display(RALL)

RALL = RALL.merge(RALL_edgeR[['locus_name', 'FC1_edgeR']], on='locus_name', how='left')

RALL = RALL.merge(RALL_DESeq2[['locus_name', 'FC1_DESeq2']], on='locus_name', how='left')

# RALL.to_csv('results_RALL.csv')



RALL

     locus_name  FC1_bayexpress FC1_edgeR FC1_DESeq2
0      15S_rRNA           False       NaN      False
1      21S_rRNA           False     False      False
2          HRA1           False       NaN      False
3          ICR1           False     False      False
4          LSR1           False     False      False
...         ...             ...       ...        ...
7121  tY(GUA)J2           False       NaN      False
7122  tY(GUA)M1           False       NaN      False
7123  tY(GUA)M2           False       NaN      False
7124   tY(GUA)O           False       NaN      False
7125   tY(GUA)Q           False       NaN        NaN

[7126 rows x 4 columns]

In [7]:
# counts (watch the NaNs!)

display(RALL.FC1_bayexpress.value_counts(dropna=False))

display(RALL.FC1_edgeR.value_counts(dropna=False))

display(RALL.FC1_DESeq2.value_counts(dropna=False))

FC1_bayexpress
False    6593
True      533
Name: count, dtype: int64

FC1_edgeR
False    5653
NaN      1032
True      441
Name: count, dtype: int64

FC1_DESeq2
False    6343
True      542
NaN       241
Name: count, dtype: int64

----------

# 20/20

In [8]:
# all bayexpress results
# 20 replicates

R20_bayexpress = pd.read_csv(f'DGE_results/R20_1_bayexpress.csv').iloc[:,1:2]

R20_bayexpress_FC1 = pd.read_csv(f'DGE_results/R20_1_bayexpress.csv').iloc[:,1:2]
R20_bayexpress_BF_21 = pd.read_csv(f'DGE_results/R20_1_bayexpress.csv').iloc[:,1:2]


for i in range(1,101):

    data = pd.read_csv(f'DGE_results/R20_{i}_bayexpress.csv').iloc[:,1:]

    # criteria 1 for significance: (BF_21 > 1) & (abs(FC) > 1)
    R20_bayexpress_FC1[f'{i}'] = (data.BF_21 > 1) & (abs(data.FC) > 1)

    R20_bayexpress_BF_21[f'{i}'] = (data.BF_21 > 1)

    R20_bayexpress[f'BF_21{i}'] = data.BF_21
    R20_bayexpress[f'FC{i}'] = data.FC

display(R20_bayexpress_FC1)
display(R20_bayexpress_BF_21)
display(R20_bayexpress)

# R20_bayexpress_FC1.set_index('locus_name').transpose().describe().loc['freq']

display(R20_bayexpress_FC1.set_index('locus_name').transpose().describe())

R20_bayexpress_FC1_True = [(R20_bayexpress_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R20_bayexpress_FC1))]
R20_bayexpress_BF_21_True = [(R20_bayexpress_BF_21.iloc[i].value_counts().get(True, 0)) for i in range(len(R20_bayexpress_BF_21))]

/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/956909624.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_bayexpress[f'BF_21{i}'] = data.BF_21

,locus_name,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,15S_rRNA,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
1,21S_rRNA,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,HRA1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,ICR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,LSR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7122,tY(GUA)M1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7123,tY(GUA)M2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7124,tY(GUA)O,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7125,tY(GUA)Q,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

,locus_name,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,15S_rRNA,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
1,21S_rRNA,False,True,False,False,True,False,True,True,True,...,False,False,False,False,True,True,False,False,True,False
2,HRA1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,ICR1,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,LSR1,False,False,False,False,False,False,True,True,True,...,False,False,True,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7122,tY(GUA)M1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7123,tY(GUA)M2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7124,tY(GUA)O,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7125,tY(GUA)Q,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

,locus_name,BF_211,FC1,BF_212,FC2,BF_213,FC3,BF_214,FC4,BF_215,...,BF_2196,FC96,BF_2197,FC97,BF_2198,FC98,BF_2199,FC99,BF_21100,FC100
0,15S_rRNA,0.177046,0.548731,-2.263158,-0.571144,-5.189158,-0.269190,-5.951314,-0.205015,-6.408289,...,0.780804,-0.782896,-6.188849,0.108497,-6.456559,-0.006482,28.990643,1.422531,-3.148582,0.396412
1,21S_rRNA,-4.704980,0.103561,24.266339,-0.607926,-4.502214,-0.116845,-4.754097,-0.127219,8.647555,...,30.014692,-0.670136,-4.568890,-0.113003,-6.040503,-0.005357,101.854919,1.022138,-2.273845,0.181025
2,HRA1,-6.377164,-0.422011,-6.476037,-0.364505,-5.449784,-0.734921,-4.283710,-0.964007,-6.414139,...,-6.531565,-0.368798,-5.569007,-0.690195,-5.377221,-0.733011,-4.357920,-1.005709,-5.419655,-0.732748
3,ICR1,23.758723,0.440980,29.727297,0.494284,39.652929,0.570578,30.012085,0.482539,27.625031,...,38.653817,0.537406,34.339070,0.529475,22.631325,0.435324,36.381089,0.526547,32.244785,0.500186
4,LSR1,-1.726704,0.135837,-5.001609,-0.070281,-4.459054,-0.083458,-5.212274,0.062253,-5.681004,...,-5.715015,-0.033265,-5.554479,-0.039649,-5.871315,-0.009598,56.980996,0.557686,-5.796581,0.017531
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,-7.386861,0.835787,-7.262532,0.430250,-7.508275,0.471531,-7.291048,-1.140885,-7.143564,...,-7.441067,-0.060676,-7.329454,-0.497550,-7.275492,0.552392,-7.638594,-0.005708,-7.253691,0.626655
7122,tY(GUA)M1,-7.146161,-0.526783,-6.150912,1.645263,-7.135058,0.346000,-7.128845,-0.462813,-7.240435,...,-7.247584,0.109249,-6.130814,1.824379,-7.069576,-0.447608,-7.261601,0.186937,-7.165519,0.179196
7123,tY(GUA)M2,-7.538939,0.420750,-7.508511,-0.055177,-7.428423,0.301606,-7.451057,0.274153,-7.362385,...,-7.070813,1.939324,-7.469843,-0.760584,-7.499881,-0.032571,-7.513653,-0.005708,-7.494277,0.626655
7124,tY(GUA)O,-7.513519,-0.164213,-7.174165,0.944823,-7.394277,-0.528469,-7.451057,0.274153,-7.527307,...,-7.645571,-0.060676,-7.342612,0.561344,-7.305510,0.704395,-7.435330,0.409329,-7.004605,2.041693
7125,tY(GUA)Q,-7.942300,-0.164213,-7.934797,-0.055177,-7.918177,-0.113432,-7.937589,-0.140885,-7.953418,...,-7.946793,-0.060676,-7.924657,-0.175622,-7.925960,-0.032571,-7.939625,-0.005708,-7.926657,0.041693

locus_name,15S_rRNA,21S_rRNA,HRA1,ICR1,LSR1,NME1,PWR1,Q0010,Q0017,Q0032,...,tX(XXX)D,tY(GUA)D,tY(GUA)F1,tY(GUA)F2,tY(GUA)J1,tY(GUA)J2,tY(GUA)M1,tY(GUA)M2,tY(GUA)O,tY(GUA)Q
count,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
unique,2,2,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
top,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,95,98,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100

In [9]:
# all edgeR results
# 20 replicates


R20_edgeR_FC1 = pd.read_csv(f'DGE_results/R20_1_edgeR.csv').iloc[:,:1]

for i in range(1,101):

    data = pd.read_csv(f'DGE_results/R20_{i}_edgeR.csv')

    # criteria 1 for significance: (pvalue < 0.05) & (abs(log2FoldChange) > 1)
    R20_edgeR_FC1[f'{i}'] = (data.PValue < 0.05) & (abs(data.logFC) > 1)


R20_edgeR_FC1['#R20'] = [(R20_edgeR_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R20_edgeR_FC1))]

display(R20_edgeR_FC1)

display(R20_edgeR_FC1.set_index('genes').transpose().describe())

/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/1228812454.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_edgeR_FC1[f'{i}'] = (data.PValue < 0.05) & (abs(data.logFC) > 1)
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/1228812454.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_edgeR_FC1['#R20'] = [(R20_edgeR_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R20_edgeR_FC1))]

,genes,1,2,3,4,5,6,7,8,9,...,92,93,94,95,96,97,98,99,100,#R20
0,YML123C,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
1,YDR033W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
2,YIL121W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
3,YOR290C,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
4,YGR234W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6096,YGL232W,False,False,NaN,NaN,False,NaN,False,False,NaN,...,False,NaN,False,NaN,False,NaN,NaN,False,False,0
6097,YPR189W,False,False,NaN,NaN,False,NaN,False,False,NaN,...,False,NaN,False,NaN,False,NaN,NaN,False,False,0
6098,YDR540C,False,False,NaN,NaN,False,NaN,False,NaN,NaN,...,False,NaN,False,NaN,False,NaN,NaN,False,False,0
6099,YGL144C,False,False,NaN,NaN,False,NaN,False,NaN,NaN,...,False,NaN,NaN,NaN,False,NaN,NaN,False,False,0
6100,YFL034C-B,False,False,NaN,NaN,NaN,NaN,False,NaN,NaN,...,False,NaN,NaN,NaN,False,NaN,NaN,False,False,0

genes,YML123C,YDR033W,YIL121W,YOR290C,YGR234W,YHR215W,YAR071W,YER081W,YER138C,YJR029W,...,YDL078C,YLL019C,YPL111W,YKR067W,YML117W,YGL232W,YPR189W,YDR540C,YGL144C,YFL034C-B
count,101,101,101,101,101,101,101,101,101,101,...,84,83,79,76,73,68,65,57,54,49
unique,2,2,2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
top,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
freq,100,100,100,100,100,100,100,100,100,100,...,84,83,79,76,73,68,65,57,54,49

In [10]:
# 20 replicates
# all DESeq2 results

R20_DESeq2_FC1 = pd.read_csv(f'DGE_results/R20_1_DESeq2.csv').iloc[:,0:1].rename(columns={'Unnamed: 0': "genes"})


for i in range(1,101):

    data = pd.read_csv(f'DGE_results/R20_{i}_DESeq2.csv')

    # criteria 1 for significance: (pvalue < 0.05) & (abs(log2FoldChange) > 1)
    R20_DESeq2_FC1[f'{i}'] = (data.pvalue < 0.05) & (abs(data.log2FoldChange) > 1)


R20_DESeq2_FC1['#R20'] = [(R20_DESeq2_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R20_DESeq2_FC1))]

display(R20_DESeq2_FC1)

display(R20_DESeq2_FC1.set_index('genes').transpose().describe())

/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/4089851359.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_DESeq2_FC1[f'{i}'] = (data.pvalue < 0.05) & (abs(data.log2FoldChange) > 1)
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/4089851359.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R20_DESeq2_FC1['#R20'] = [(R20_DESeq2_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R20_DESeq2_FC1))]

,genes,1,2,3,4,5,6,7,8,9,...,92,93,94,95,96,97,98,99,100,#R20
0,15S_rRNA,False,False,False,False,False,False,True,False,False,...,False,False,False,True,True,False,False,False,False,7
1,21S_rRNA,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,10
2,HRA1,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,28
3,ICR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
4,LSR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7122,tY(GUA)M1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7123,tY(GUA)M2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7124,tY(GUA)O,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7125,tY(GUA)Q,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0

genes,15S_rRNA,21S_rRNA,HRA1,ICR1,LSR1,NME1,PWR1,Q0010,Q0017,Q0032,...,tX(XXX)D,tY(GUA)D,tY(GUA)F1,tY(GUA)F2,tY(GUA)J1,tY(GUA)J2,tY(GUA)M1,tY(GUA)M2,tY(GUA)O,tY(GUA)Q
count,101,101,101,101,101,101,101,101,101,101,...,101,101,101,101,101,101,101,101,101,101
unique,3,3,3,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
top,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,93,90,72,101,101,101,101,101,101,101,...,101,101,101,101,101,101,101,101,101,101

# 12/12

In [11]:
# all bayexpress results
# 12 replicates

R12_bayexpress = pd.read_csv(f'DGE_results/R12_1_bayexpress.csv').iloc[:,1:2]

R12_bayexpress_FC1 = pd.read_csv(f'DGE_results/R12_1_bayexpress.csv').iloc[:,1:2]
R12_bayexpress_BF_21 = pd.read_csv(f'DGE_results/R12_1_bayexpress.csv').iloc[:,1:2]


for i in range(1,101):

    data = pd.read_csv(f'DGE_results/R12_{i}_bayexpress.csv').iloc[:,1:]

    # criteria 1 for significance: (BF_21 > 1) & (abs(FC) > 1)
    R12_bayexpress_FC1[f'{i}'] = (data.BF_21 > 1) & (abs(data.FC) > 1)

    R12_bayexpress_BF_21[f'{i}'] = (data.BF_21 > 1)

    R12_bayexpress[f'BF_21{i}'] = data.BF_21
    R12_bayexpress[f'FC{i}'] = data.FC

display(R12_bayexpress_FC1)
display(R12_bayexpress_BF_21)
display(R12_bayexpress)

# R12_bayexpress_FC1.set_index('locus_name').transpose().describe().loc['freq']

display(R12_bayexpress_FC1.set_index('locus_name').transpose().describe())

R12_bayexpress_FC1_True = [(R12_bayexpress_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R12_bayexpress_FC1))]
R12_bayexpress_BF_21_True = [(R12_bayexpress_BF_21.iloc[i].value_counts().get(True, 0)) for i in range(len(R12_bayexpress_BF_21))]

/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/192629054.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_bayexpress[f'BF_21{i}'] = data.BF_21

,locus_name,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,15S_rRNA,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,True,False,False,False
1,21S_rRNA,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
2,HRA1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,ICR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,LSR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7122,tY(GUA)M1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7123,tY(GUA)M2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7124,tY(GUA)O,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7125,tY(GUA)Q,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

,locus_name,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,15S_rRNA,False,False,False,False,False,True,False,False,True,...,False,True,False,True,True,False,True,False,False,False
1,21S_rRNA,True,False,False,True,False,True,True,True,True,...,True,True,False,True,True,False,True,False,False,False
2,HRA1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,ICR1,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,LSR1,True,False,False,False,False,True,True,True,True,...,True,False,False,True,True,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7122,tY(GUA)M1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7123,tY(GUA)M2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7124,tY(GUA)O,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7125,tY(GUA)Q,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

,locus_name,BF_211,FC1,BF_212,FC2,BF_213,FC3,BF_214,FC4,BF_215,...,BF_2196,FC96,BF_2197,FC97,BF_2198,FC98,BF_2199,FC99,BF_21100,FC100
0,15S_rRNA,-3.492943,0.703255,-3.034932,-0.515738,-3.132248,-0.598927,-0.631445,-0.853216,-4.109536,...,-5.337514,0.389384,29.949236,1.658484,-6.342792,-0.054922,-5.550147,0.291637,-4.652154,-0.494020
1,21S_rRNA,12.780156,0.631570,-4.475839,-0.136107,-0.349699,-0.312720,1.713753,-0.376004,-0.530458,...,-5.080317,0.152426,136.576277,1.427636,-5.261814,0.120020,-5.880033,0.033149,-0.207251,-0.341460
2,HRA1,-4.891569,-1.136450,-6.114594,-0.664601,-5.961703,-0.642648,-6.749409,-0.116249,-5.173614,...,-6.481672,-0.349428,-3.261530,-1.483570,-5.223921,-1.014662,-6.316838,-0.510957,-5.979822,-0.706486
3,ICR1,23.350791,0.560148,23.302741,0.569220,12.411491,0.444856,14.299734,0.466080,24.086512,...,16.488266,0.484697,21.362495,0.535200,22.546651,0.555844,20.157665,0.519962,13.813194,0.475254
4,LSR1,3.918977,0.303560,-5.427432,-0.051569,-3.007651,-0.152552,-5.647106,0.038987,-5.010331,...,-4.575825,0.104336,74.537342,0.727225,6.413617,0.322157,-4.271746,0.106612,11.346705,-0.381006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,-7.298099,0.636140,-7.415290,-1.036569,-6.442292,2.438272,-6.987785,1.205679,-7.217291,...,-7.206420,0.551037,-7.740648,-0.038785,-7.415962,-0.197526,-7.217800,-0.510957,-6.912985,1.004008
7122,tY(GUA)M1,-7.055971,0.636140,-7.118150,0.226465,-7.011088,-0.246226,-7.115358,0.468713,-7.053996,...,-7.111481,-0.448963,-7.131356,-0.038785,-6.991377,-0.782488,-7.231997,-0.095920,-7.195240,-0.411030
7123,tY(GUA)M2,-7.731975,0.051177,-7.301290,0.548393,-7.273331,0.701307,-7.298712,-0.701212,-7.098004,...,-7.327506,-0.448963,-7.126834,-1.623748,-7.387248,-1.197526,-7.164921,1.489043,-7.398155,1.004008
7124,tY(GUA)O,-7.430809,0.051177,-6.835177,1.963431,-7.120687,-0.620621,-7.298712,-0.701212,-7.285436,...,-7.432457,0.135999,-7.183069,0.283143,-7.238522,0.217512,-7.164442,0.904080,-7.398758,0.004008
7125,tY(GUA)Q,-7.731975,0.051177,-7.721859,-0.036569,-7.717870,0.116344,-7.743235,-0.116249,-7.723353,...,-7.734451,0.135999,-7.740648,-0.038785,-7.719025,-0.197526,-7.738586,-0.095920,-7.699789,0.004008

locus_name,15S_rRNA,21S_rRNA,HRA1,ICR1,LSR1,NME1,PWR1,Q0010,Q0017,Q0032,...,tX(XXX)D,tY(GUA)D,tY(GUA)F1,tY(GUA)F2,tY(GUA)J1,tY(GUA)J2,tY(GUA)M1,tY(GUA)M2,tY(GUA)O,tY(GUA)Q
count,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
unique,2,2,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
top,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,85,92,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100

In [12]:
# all edgeR results
# 12 replicates


R12_edgeR_FC1 = pd.read_csv(f'DGE_results/R12_1_edgeR.csv').iloc[:,:1]

for i in range(1,101):

    data = pd.read_csv(f'DGE_results/R12_{i}_edgeR.csv')

    # criteria 1 for significance: (pvalue < 0.05) & (abs(log2FoldChange) > 1)
    R12_edgeR_FC1[f'{i}'] = (data.PValue < 0.05) & (abs(data.logFC) > 1)


R12_edgeR_FC1['#R12'] = [(R12_edgeR_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R12_edgeR_FC1))]

display(R12_edgeR_FC1)

display(R12_edgeR_FC1.set_index('genes').transpose().describe())

/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/871419072.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_edgeR_FC1[f'{i}'] = (data.PValue < 0.05) & (abs(data.logFC) > 1)
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/871419072.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_edgeR_FC1['#R12'] = [(R12_edgeR_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R12_edgeR_FC1))]

,genes,1,2,3,4,5,6,7,8,9,...,92,93,94,95,96,97,98,99,100,#R12
0,YGR234W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
1,YDR033W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
2,YAR071W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
3,YHR215W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
4,YML123C,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6088,YDL215C,False,False,False,False,NaN,False,NaN,NaN,False,...,NaN,False,False,NaN,False,False,False,False,False,0
6089,YAR033W,False,False,False,False,NaN,False,NaN,NaN,False,...,NaN,False,False,NaN,False,False,False,False,False,0
6090,YDR534C,False,NaN,False,False,NaN,NaN,NaN,NaN,NaN,...,NaN,False,False,NaN,False,False,False,False,NaN,0
6091,YGR170W,False,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,False,False,NaN,False,False,False,False,NaN,0
6092,YLR115W,False,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,False,False,NaN,False,False,False,False,NaN,0

genes,YGR234W,YDR033W,YAR071W,YHR215W,YML123C,YOR290C,YIL121W,YBR012W-B,YPL257W-B,YOL103W-B,...,YNR039C,YER158C,YOL147C,YPR118W,YOR195W,YDL215C,YAR033W,YDR534C,YGR170W,YLR115W
count,101,101,101,101,101,101,101,101,101,101,...,66,61,60,57,54,50,44,37,32,30
unique,2,2,2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
top,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
freq,100,100,100,100,100,100,100,100,100,100,...,66,61,60,57,54,50,44,37,32,30

In [13]:
# 12 replicates
# all DESeq2 results

R12_DESeq2_FC1 = pd.read_csv(f'DGE_results/R12_1_DESeq2.csv').iloc[:,0:1].rename(columns={'Unnamed: 0': "genes"})


for i in range(1,101):

    data = pd.read_csv(f'DGE_results/R12_{i}_DESeq2.csv')

    # criteria 1 for significance: (pvalue < 0.05) & (abs(log2FoldChange) > 1)
    R12_DESeq2_FC1[f'{i}'] = (data.pvalue < 0.05) & (abs(data.log2FoldChange) > 1)


R12_DESeq2_FC1['#R12'] = [(R12_DESeq2_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R12_DESeq2_FC1))]

display(R12_DESeq2_FC1)

display(R12_DESeq2_FC1.set_index('genes').transpose().describe())

/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/4222840766.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_DESeq2_FC1[f'{i}'] = (data.pvalue < 0.05) & (abs(data.log2FoldChange) > 1)
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/4222840766.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R12_DESeq2_FC1['#R12'] = [(R12_DESeq2_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R12_DESeq2_FC1))]

,genes,1,2,3,4,5,6,7,8,9,...,92,93,94,95,96,97,98,99,100,#R12
0,15S_rRNA,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,15
1,21S_rRNA,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,True,True,False,False,12
2,HRA1,True,False,False,False,True,True,False,False,False,...,False,True,False,False,False,True,True,False,False,26
3,ICR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
4,LSR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7122,tY(GUA)M1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7123,tY(GUA)M2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7124,tY(GUA)O,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7125,tY(GUA)Q,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0

genes,15S_rRNA,21S_rRNA,HRA1,ICR1,LSR1,NME1,PWR1,Q0010,Q0017,Q0032,...,tX(XXX)D,tY(GUA)D,tY(GUA)F1,tY(GUA)F2,tY(GUA)J1,tY(GUA)J2,tY(GUA)M1,tY(GUA)M2,tY(GUA)O,tY(GUA)Q
count,101,101,101,101,101,101,101,101,101,101,...,101,101,101,101,101,101,101,101,101,101
unique,3,3,3,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
top,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,85,88,74,101,101,101,101,101,101,101,...,101,101,101,101,101,101,101,101,101,101

# 6/6

In [14]:
# all bayexpress results
# 6 replicates

R6_bayexpress = pd.read_csv(f'DGE_results/R6_1_bayexpress.csv').iloc[:,1:2]

R6_bayexpress_FC1 = pd.read_csv(f'DGE_results/R6_1_bayexpress.csv').iloc[:,1:2]
R6_bayexpress_BF_21 = pd.read_csv(f'DGE_results/R6_1_bayexpress.csv').iloc[:,1:2]


for i in range(1,101):

    data = pd.read_csv(f'DGE_results/R6_{i}_bayexpress.csv').iloc[:,1:]

    # criteria 1 for significance: (BF_21 > 1) & (abs(FC) > 1)
    R6_bayexpress_FC1[f'{i}'] = (data.BF_21 > 1) & (abs(data.FC) > 1)

    R6_bayexpress_BF_21[f'{i}'] = (data.BF_21 > 1)

    R6_bayexpress[f'BF_21{i}'] = data.BF_21
    R6_bayexpress[f'FC{i}'] = data.FC

display(R6_bayexpress_FC1)
display(R6_bayexpress_BF_21)
display(R6_bayexpress)

# R6_bayexpress_FC1.set_index('locus_name').transpose().describe().loc['freq']

display(R6_bayexpress_FC1.set_index('locus_name').transpose().describe())

R6_bayexpress_FC1_True = [(R6_bayexpress_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R6_bayexpress_FC1))]
R6_bayexpress_BF_21_True = [(R6_bayexpress_BF_21.iloc[i].value_counts().get(True, 0)) for i in range(len(R6_bayexpress_BF_21))]

/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/936492552.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_bayexpress[f'BF_21{i}'] = data.BF_21

,locus_name,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,15S_rRNA,True,False,False,False,False,True,False,False,False,...,True,False,True,True,True,False,False,False,True,True
1,21S_rRNA,True,False,True,False,False,True,False,False,False,...,True,False,True,True,True,False,False,True,True,False
2,HRA1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,ICR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,LSR1,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7122,tY(GUA)M1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7123,tY(GUA)M2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7124,tY(GUA)O,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7125,tY(GUA)Q,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

,locus_name,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,15S_rRNA,True,False,False,False,False,True,False,False,False,...,True,False,True,True,True,False,False,False,True,True
1,21S_rRNA,True,True,True,False,True,True,False,True,True,...,True,False,True,True,True,False,False,True,True,True
2,HRA1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,ICR1,True,True,True,True,True,True,True,True,True,...,True,False,True,True,True,True,True,True,True,True
4,LSR1,True,True,False,True,False,True,False,False,True,...,True,False,True,False,True,False,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7122,tY(GUA)M1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7123,tY(GUA)M2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7124,tY(GUA)O,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7125,tY(GUA)Q,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

,locus_name,BF_211,FC1,BF_212,FC2,BF_213,FC3,BF_214,FC4,BF_215,...,BF_2196,FC96,BF_2197,FC97,BF_2198,FC98,BF_2199,FC99,BF_21100,FC100
0,15S_rRNA,12.481116,2.119475,-4.399265,0.572390,0.873976,-1.601953,-6.137590,-0.036249,-5.948513,...,-5.655367,-0.426128,-5.298711,-0.684669,-3.803009,-0.864634,19.748115,-2.323177,6.276698,1.643292
1,21S_rRNA,60.340200,1.703492,8.236388,0.628058,50.421996,-1.566153,-5.401460,-0.095830,11.267593,...,-4.191779,-0.267198,-4.502349,-0.306909,17.922113,-1.016590,77.994267,-1.542620,16.451948,0.885499
2,HRA1,-6.369652,-0.458605,-6.553735,0.518751,-6.508032,-0.138060,-5.935681,-0.744383,-5.508599,...,-6.572584,0.227783,-6.333542,-0.478349,-6.322248,-0.625167,-6.507671,-0.537844,-6.379588,-0.351549
3,ICR1,8.789220,0.550099,15.813020,0.722012,8.682366,0.568929,4.884509,0.451793,9.948983,...,1.509575,0.408713,10.828200,0.601675,6.794914,0.534834,6.701814,0.510334,1.604746,0.382298
4,LSR1,15.807431,0.582134,87.703051,1.343500,-3.676807,-0.203405,14.696048,-0.504708,-0.036162,...,-0.781959,-0.299982,4.044987,-0.431521,10.771369,-0.581364,41.455637,-0.839459,-5.601488,0.029809
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,-7.081683,-1.298140,-7.109006,-0.258856,-6.664668,1.650436,-6.973592,0.283631,-6.867154,...,-6.992005,0.606294,-6.564662,1.913969,-7.083323,0.052905,-6.901859,1.310153,-6.869586,-1.573941
7122,tY(GUA)M1,-7.124243,-0.298140,-7.021284,0.326106,-7.167858,0.650436,-6.934034,-0.546444,-6.926898,...,-6.995204,0.021332,-6.989988,-0.670994,-6.966275,-0.532058,-6.732473,-1.274809,-6.903511,0.332949
7123,tY(GUA)M2,-7.171432,0.701860,-7.413527,-0.258856,-7.419452,-0.349564,-7.139955,-1.131406,-7.069465,...,-7.421220,0.021332,-7.128068,-0.086031,-7.091359,-0.947095,-7.425126,-0.274809,-7.468334,0.011021
7124,tY(GUA)O,-7.429902,-0.298140,-7.413527,-0.258856,-7.419452,-0.349564,-7.139955,-1.131406,-7.405105,...,-7.123389,-0.978668,-7.115312,-1.086031,-7.083323,0.052905,-6.901859,1.310153,-7.168960,-0.988979
7125,tY(GUA)Q,-7.429902,-0.298140,-7.413527,-0.258856,-7.419452,-0.349564,-7.461214,-0.131406,-7.405105,...,-7.421220,0.021332,-7.429484,-0.086031,-7.384499,0.052905,-7.425126,-0.274809,-7.468334,0.011021

locus_name,15S_rRNA,21S_rRNA,HRA1,ICR1,LSR1,NME1,PWR1,Q0010,Q0017,Q0032,...,tX(XXX)D,tY(GUA)D,tY(GUA)F1,tY(GUA)F2,tY(GUA)J1,tY(GUA)J2,tY(GUA)M1,tY(GUA)M2,tY(GUA)O,tY(GUA)Q
count,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
unique,2,2,1,1,2,2,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
top,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,76,73,100,100,98,98,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100

In [15]:
# all edgeR results
# 6 replicates


R6_edgeR_FC1 = pd.read_csv(f'DGE_results/R6_1_edgeR.csv').iloc[:,:1]

for i in range(1,101):

    data = pd.read_csv(f'DGE_results/R6_{i}_edgeR.csv')

    # criteria 1 for significance: (pvalue < 0.05) & (abs(log2FoldChange) > 1)
    R6_edgeR_FC1[f'{i}'] = (data.PValue < 0.05) & (abs(data.logFC) > 1)


R6_edgeR_FC1['#R6'] = [(R6_edgeR_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R6_edgeR_FC1))]

display(R6_edgeR_FC1)

display(R6_edgeR_FC1.set_index('genes').transpose().describe())

/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/1541180151.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_edgeR_FC1[f'{i}'] = (data.PValue < 0.05) & (abs(data.logFC) > 1)
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/1541180151.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_edgeR_FC1['#R6'] = [(R6_edgeR_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R6_edgeR_FC1))]

,genes,1,2,3,4,5,6,7,8,9,...,92,93,94,95,96,97,98,99,100,#R6
0,YHR215W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
1,YAR071W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
2,YGR234W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
3,YIL121W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
4,YML123C,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6095,YNL243W,False,NaN,False,False,False,NaN,NaN,NaN,False,...,NaN,False,False,NaN,NaN,False,NaN,NaN,False,0
6096,YGR294W,False,NaN,False,False,False,NaN,NaN,NaN,False,...,NaN,False,False,NaN,NaN,False,NaN,NaN,False,0
6097,YPL258C,False,NaN,False,False,False,NaN,NaN,NaN,NaN,...,NaN,False,False,NaN,NaN,False,NaN,NaN,False,0
6098,YER189W,False,NaN,False,False,False,NaN,NaN,NaN,NaN,...,NaN,False,False,NaN,NaN,False,NaN,NaN,False,0
6099,YBR280C,False,NaN,False,False,False,NaN,NaN,NaN,NaN,...,NaN,False,False,NaN,NaN,False,NaN,NaN,False,0

genes,YHR215W,YAR071W,YGR234W,YIL121W,YML123C,YDR033W,YPL019C,YOR290C,YER011W,YER081W,...,YML072C,YLR251W,YGR213C,YDL074C,YPL022W,YNL243W,YGR294W,YPL258C,YER189W,YBR280C
count,101,101,101,101,101,101,101,101,101,101,...,58,57,56,56,55,54,52,50,49,48
unique,2,2,2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
top,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
freq,100,100,100,100,100,100,100,100,100,100,...,58,57,56,56,55,54,52,50,49,48

In [16]:
# 6 replicates
# all DESeq2 results

R6_DESeq2_FC1 = pd.read_csv(f'DGE_results/R6_1_DESeq2.csv').iloc[:,0:1].rename(columns={'Unnamed: 0': "genes"})


for i in range(1,101):

    data = pd.read_csv(f'DGE_results/R6_{i}_DESeq2.csv')

    # criteria 1 for significance: (pvalue < 0.05) & (abs(log2FoldChange) > 1)
    R6_DESeq2_FC1[f'{i}'] = (data.pvalue < 0.05) & (abs(data.log2FoldChange) > 1)


R6_DESeq2_FC1['#R6'] = [(R6_DESeq2_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R6_DESeq2_FC1))]

display(R6_DESeq2_FC1)

display(R6_DESeq2_FC1.set_index('genes').transpose().describe())

/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/855214188.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_DESeq2_FC1[f'{i}'] = (data.pvalue < 0.05) & (abs(data.log2FoldChange) > 1)
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/855214188.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R6_DESeq2_FC1['#R6'] = [(R6_DESeq2_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R6_DESeq2_FC1))]

,genes,1,2,3,4,5,6,7,8,9,...,92,93,94,95,96,97,98,99,100,#R6
0,15S_rRNA,True,False,True,False,False,False,False,False,False,...,False,True,True,True,False,False,True,True,False,20
1,21S_rRNA,True,False,True,False,False,False,False,False,False,...,False,False,True,True,False,False,True,True,False,21
2,HRA1,False,False,False,False,False,False,False,False,True,...,False,True,False,False,False,False,False,False,False,17
3,ICR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
4,LSR1,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,True,False,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7122,tY(GUA)M1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7123,tY(GUA)M2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7124,tY(GUA)O,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7125,tY(GUA)Q,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0

genes,15S_rRNA,21S_rRNA,HRA1,ICR1,LSR1,NME1,PWR1,Q0010,Q0017,Q0032,...,tX(XXX)D,tY(GUA)D,tY(GUA)F1,tY(GUA)F2,tY(GUA)J1,tY(GUA)J2,tY(GUA)M1,tY(GUA)M2,tY(GUA)O,tY(GUA)Q
count,101,101,101,101,101,101,101,101,101,101,...,101,101,101,101,101,101,101,101,101,101
unique,3,3,3,1,3,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
top,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,80,79,83,101,94,101,101,101,101,101,...,101,101,101,101,101,101,101,101,101,101

# 3/3

In [17]:
# all bayexpress results
# 3 replicates

R3_bayexpress = pd.read_csv(f'DGE_results/R3_1_bayexpress.csv').iloc[:,1:2]

R3_bayexpress_FC1 = pd.read_csv(f'DGE_results/R3_1_bayexpress.csv').iloc[:,1:2]
R3_bayexpress_BF_21 = pd.read_csv(f'DGE_results/R3_1_bayexpress.csv').iloc[:,1:2]


for i in range(1,101):

    data = pd.read_csv(f'DGE_results/R3_{i}_bayexpress.csv').iloc[:,1:]

    # criteria 1 for significance: (BF_21 > 1) & (abs(FC) > 1)
    R3_bayexpress_FC1[f'{i}'] = (data.BF_21 > 1) & (abs(data.FC) > 1)

    R3_bayexpress_BF_21[f'{i}'] = (data.BF_21 > 1)

    R3_bayexpress[f'BF_21{i}'] = data.BF_21
    R3_bayexpress[f'FC{i}'] = data.FC

display(R3_bayexpress_FC1)
display(R3_bayexpress_BF_21)
display(R3_bayexpress)

# R3_bayexpress_FC1.set_index('locus_name').transpose().describe().loc['freq']

display(R3_bayexpress_FC1.set_index('locus_name').transpose().describe())

R3_bayexpress_FC1_True = [(R3_bayexpress_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R3_bayexpress_FC1))]
R3_bayexpress_BF_21_True = [(R3_bayexpress_BF_21.iloc[i].value_counts().get(True, 0)) for i in range(len(R3_bayexpress_BF_21))]

/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'FC{i}'] = data.FC
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/2507426500.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_bayexpress[f'BF_21{i}'] = data.BF_21

,locus_name,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,15S_rRNA,True,True,False,False,False,False,True,True,False,...,True,False,False,True,True,False,False,False,False,True
1,21S_rRNA,True,True,False,True,False,True,True,True,False,...,True,False,False,True,True,False,False,True,False,True
2,HRA1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,ICR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,LSR1,False,False,False,False,False,False,False,False,False,...,True,False,False,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7122,tY(GUA)M1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7123,tY(GUA)M2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7124,tY(GUA)O,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7125,tY(GUA)Q,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

,locus_name,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,15S_rRNA,True,True,False,False,False,False,True,True,False,...,True,False,False,True,True,False,False,False,False,True
1,21S_rRNA,True,True,False,True,True,True,True,True,False,...,True,False,False,True,True,False,False,True,False,True
2,HRA1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,ICR1,False,False,False,False,False,False,True,True,True,...,False,True,False,False,True,True,False,True,False,False
4,LSR1,True,True,False,True,False,True,True,True,False,...,True,True,True,True,True,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7122,tY(GUA)M1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7123,tY(GUA)M2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7124,tY(GUA)O,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7125,tY(GUA)Q,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

,locus_name,BF_211,FC1,BF_212,FC2,BF_213,FC3,BF_214,FC4,BF_215,...,BF_2196,FC96,BF_2197,FC97,BF_2198,FC98,BF_2199,FC99,BF_21100,FC100
0,15S_rRNA,19.599095,2.044385,9.976490,2.073428,-5.752492,-0.570419,-2.518659,1.409593,-5.087074,...,-5.254968,-1.012398,-2.851120,1.722186,-2.343497,1.459914,-5.425035,-0.413082,18.792073,1.853810
1,21S_rRNA,36.594655,1.173451,34.067293,1.437238,-4.694255,-0.360404,27.972882,1.617320,1.837220,...,-5.173513,-0.338093,0.149826,0.906798,27.466899,1.602153,-5.159034,0.140564,59.554872,1.481208
2,HRA1,-6.410007,-0.236452,-6.254598,0.581570,-5.674198,-1.432915,-4.951867,-1.758646,-6.475123,...,-6.216074,-0.642447,-6.086901,-0.599744,-6.209753,-0.614089,-6.162399,0.704276,-6.399453,-0.600766
3,ICR1,-1.283395,0.430460,-1.647052,0.388042,-3.580944,0.280443,-0.616224,0.472525,0.695496,...,4.351522,0.669829,0.242279,0.535042,13.296120,0.898007,-2.718674,0.344815,0.247616,0.463373
4,LSR1,4.343989,0.430381,2.129219,0.450415,-5.540210,-0.027970,8.546345,0.702674,-4.190642,...,-5.410634,-0.062015,-5.118154,0.113157,41.938536,1.304268,-5.100919,-0.096990,13.988333,0.593365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,-6.473857,1.711081,-6.631307,-1.418431,-7.152870,0.152048,-7.095961,-0.273219,-6.949086,...,-6.531837,1.457089,-7.091600,0.137222,-6.888302,0.800949,-6.590371,1.289239,-6.641482,-1.185728
7122,tY(GUA)M1,-6.832250,-0.873882,-6.781610,-0.418430,-6.502629,1.152048,-6.662216,-0.273219,-6.721707,...,-6.794373,-0.127874,-6.643505,0.722185,-6.857309,-0.199051,-6.630652,-0.880686,-6.689104,0.399234
7123,tY(GUA)M2,-6.832250,-0.873882,-7.184682,0.166532,-7.152870,0.152048,-6.572260,1.311744,-7.204305,...,-7.096256,-0.127874,-6.789588,0.137222,-6.888302,0.800949,-6.849167,0.704276,-7.131649,0.399234
7124,tY(GUA)O,-6.832250,-0.873882,-7.184682,0.166532,-7.152870,0.152048,-6.751863,-1.273219,-7.204305,...,-7.096256,-0.127874,-6.810733,-0.862778,-6.828381,-1.199051,-6.760145,-1.295724,-7.131649,0.399234
7125,tY(GUA)Q,-7.114712,0.126118,-7.184682,0.166532,-7.152870,0.152048,-7.095961,-0.273219,-7.204305,...,-7.096256,-0.127874,-7.091600,0.137222,-7.160404,-0.199051,-7.107963,-0.295724,-7.131649,0.399234

locus_name,15S_rRNA,21S_rRNA,HRA1,ICR1,LSR1,NME1,PWR1,Q0010,Q0017,Q0032,...,tX(XXX)D,tY(GUA)D,tY(GUA)F1,tY(GUA)F2,tY(GUA)J1,tY(GUA)J2,tY(GUA)M1,tY(GUA)M2,tY(GUA)O,tY(GUA)Q
count,100,100,100,100,100,100,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100
unique,2,2,1,1,2,2,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
top,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,70,54,100,100,82,93,100,100,100,100,...,100,100,100,100,100,100,100,100,100,100

In [18]:
# all edgeR results
# 3 replicates


R3_edgeR_FC1 = pd.read_csv(f'DGE_results/R3_1_edgeR.csv').iloc[:,:1]

for i in range(1,101):

    data = pd.read_csv(f'DGE_results/R3_{i}_edgeR.csv')

    # criteria 1 for significance: (pvalue < 0.05) & (abs(log2FoldChange) > 1)
    R3_edgeR_FC1[f'{i}'] = (data.PValue < 0.05) & (abs(data.logFC) > 1)


R3_edgeR_FC1['#R3'] = [(R3_edgeR_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R3_edgeR_FC1))]

display(R3_edgeR_FC1)

display(R3_edgeR_FC1.set_index('genes').transpose().describe())

/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/1733856150.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_edgeR_FC1[f'{i}'] = (data.PValue < 0.05) & (abs(data.logFC) > 1)
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/1733856150.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_edgeR_FC1['#R3'] = [(R3_edgeR_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R3_edgeR_FC1))]

,genes,1,2,3,4,5,6,7,8,9,...,92,93,94,95,96,97,98,99,100,#R3
0,YHR215W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
1,YOR290C,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
2,YAR071W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
3,YDR033W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
4,YER081W,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6110,YIL157C,False,False,False,NaN,False,False,False,False,NaN,...,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,0
6111,YOR061W,False,False,False,NaN,False,False,False,False,NaN,...,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,0
6112,YOR007C,False,False,False,NaN,False,False,False,False,NaN,...,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,0
6113,YJR031C,False,False,False,NaN,False,False,False,False,NaN,...,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,0
6114,YMR218C,False,False,False,NaN,False,False,False,False,NaN,...,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,0

genes,YHR215W,YOR290C,YAR071W,YDR033W,YER081W,YIL121W,YPL019C,YPL257W-B,YGR234W,YML123C,...,YIL090W,YDR205W,YGR247W,YNR004W,YKL144C,YIL157C,YOR061W,YOR007C,YJR031C,YMR218C
count,101,101,101,101,101,101,101,101,101,101,...,63,62,60,58,57,56,54,53,52,51
unique,2,2,2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1
top,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
freq,100,100,100,100,100,100,100,100,100,100,...,63,62,60,58,57,56,54,53,52,51

In [19]:
# 3 replicates
# all DESeq2 results

R3_DESeq2_FC1 = pd.read_csv(f'DGE_results/R3_1_DESeq2.csv').iloc[:,0:1].rename(columns={'Unnamed: 0': "genes"})


for i in range(1,101):

    data = pd.read_csv(f'DGE_results/R3_{i}_DESeq2.csv')

    # criteria 1 for significance: (pvalue < 0.05) & (abs(log2FoldChange) > 1)
    R3_DESeq2_FC1[f'{i}'] = (data.pvalue < 0.05) & (abs(data.log2FoldChange) > 1)


R3_DESeq2_FC1['#R3'] = [(R3_DESeq2_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R3_DESeq2_FC1))]

display(R3_DESeq2_FC1)

display(R3_DESeq2_FC1.set_index('genes').transpose().describe())

/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/760640590.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_DESeq2_FC1[f'{i}'] = (data.pvalue < 0.05) & (abs(data.log2FoldChange) > 1)
/var/folders/dl/6r82c34d3pbdmnyfpk1l0ff00000gn/T/ipykernel_43477/760640590.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  R3_DESeq2_FC1['#R3'] = [(R3_DESeq2_FC1.iloc[i].value_counts().get(True, 0)) for i in range(len(R3_DESeq2_FC1))]

,genes,1,2,3,4,5,6,7,8,9,...,92,93,94,95,96,97,98,99,100,#R3
0,15S_rRNA,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,23
1,21S_rRNA,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,25
2,HRA1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
3,ICR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
4,LSR1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7121,tY(GUA)J2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7122,tY(GUA)M1,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7123,tY(GUA)M2,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7124,tY(GUA)O,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0
7125,tY(GUA)Q,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0

genes,15S_rRNA,21S_rRNA,HRA1,ICR1,LSR1,NME1,PWR1,Q0010,Q0017,Q0032,...,tX(XXX)D,tY(GUA)D,tY(GUA)F1,tY(GUA)F2,tY(GUA)J1,tY(GUA)J2,tY(GUA)M1,tY(GUA)M2,tY(GUA)O,tY(GUA)Q
count,101,101,101,101,101,101,101,101,101,101,...,101,101,101,101,101,101,101,101,101,101
unique,3,3,1,1,3,3,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
top,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,77,75,101,101,97,94,101,101,101,101,...,101,101,101,101,101,101,101,101,101,101

In [20]:
bayexpress_BF_21Ntrue = pd.DataFrame({ 
    '#3R': R3_bayexpress_BF_21_True,
    '#6R': R6_bayexpress_BF_21_True,
    '#12R': R12_bayexpress_BF_21_True,
    '#20R': R20_bayexpress_BF_21_True}, 
    index=R3_bayexpress.locus_name)

bayexpress_BF_21Ntrue.to_csv('bayexpress_BF_21Ntrue.csv')

display(bayexpress_BF_21Ntrue)

            #3R  #6R  #12R  #20R
locus_name
15S_rRNA     30   25    24    21
21S_rRNA     67   53    63    54
HRA1          0    0     0     0
ICR1         45   91    99   100
LSR1         51   46    39    41
...         ...  ...   ...   ...
tY(GUA)J2     0    0     0     0
tY(GUA)M1     0    0     0     0
tY(GUA)M2     0    0     0     0
tY(GUA)O      0    0     0     0
tY(GUA)Q      0    0     0     0

[7126 rows x 4 columns]

In [21]:
bayexpress_Ntrue = pd.DataFrame({ 
    '#3R': R3_bayexpress_FC1_True,
    '#6R': R6_bayexpress_FC1_True,
    '#12R': R12_bayexpress_FC1_True,
    '#20R': R20_bayexpress_FC1_True}, 
    index=R3_bayexpress.locus_name)

bayexpress_Ntrue.to_csv('bayexpress_Ntrue.csv')

display(bayexpress_Ntrue)

            #3R  #6R  #12R  #20R
locus_name
15S_rRNA     30   24    15     5
21S_rRNA     54   27     8     2
HRA1          0    0     0     0
ICR1          0    0     0     0
LSR1         18    2     0     0
...         ...  ...   ...   ...
tY(GUA)J2     0    0     0     0
tY(GUA)M1     0    0     0     0
tY(GUA)M2     0    0     0     0
tY(GUA)O      0    0     0     0
tY(GUA)Q      0    0     0     0

[7126 rows x 4 columns]

In [22]:
edgeR_Ntrue = pd.DataFrame({'genes': R3_bayexpress.locus_name})

edgeR_Ntrue = edgeR_Ntrue.merge(R3_edgeR_FC1[['genes', '#R3']], on='genes', how='left')

edgeR_Ntrue = edgeR_Ntrue.merge(R6_edgeR_FC1[['genes', '#R6']], on='genes', how='left')

edgeR_Ntrue = edgeR_Ntrue.merge(R12_edgeR_FC1[['genes', '#R12']], on='genes', how='left')

edgeR_Ntrue = edgeR_Ntrue.merge(R20_edgeR_FC1[['genes', '#R20']], on='genes', how='left')


edgeR_Ntrue = edgeR_Ntrue.set_index('genes').replace(np.nan, 0)

edgeR_Ntrue['#R3'] = edgeR_Ntrue['#R3'].astype('int')

edgeR_Ntrue['#R6'] = edgeR_Ntrue['#R6'].astype('int')

edgeR_Ntrue['#R12'] = edgeR_Ntrue['#R12'].astype('int')

edgeR_Ntrue['#R20'] = edgeR_Ntrue['#R20'].astype('int')


edgeR_Ntrue.to_csv('edgeR_Ntrue.csv')

edgeR_Ntrue

           #R3  #R6  #R12  #R20
genes
15S_rRNA     0    0     0     0
21S_rRNA     0    1     0     0
HRA1         0    0     0     0
ICR1         0    0     0     0
LSR1         0    0     0     0
...        ...  ...   ...   ...
tY(GUA)J2    0    0     0     0
tY(GUA)M1    0    0     0     0
tY(GUA)M2    0    0     0     0
tY(GUA)O     0    0     0     0
tY(GUA)Q     0    0     0     0

[7126 rows x 4 columns]

In [23]:
DESeq2_Ntrue = pd.DataFrame({'genes': R3_bayexpress.locus_name})

DESeq2_Ntrue = DESeq2_Ntrue.merge(R3_DESeq2_FC1[['genes', '#R3']], on='genes', how='left')

DESeq2_Ntrue = DESeq2_Ntrue.merge(R6_DESeq2_FC1[['genes', '#R6']], on='genes', how='left')

DESeq2_Ntrue = DESeq2_Ntrue.merge(R12_DESeq2_FC1[['genes', '#R12']], on='genes', how='left')

DESeq2_Ntrue = DESeq2_Ntrue.merge(R20_DESeq2_FC1[['genes', '#R20']], on='genes', how='left')

DESeq2_Ntrue = DESeq2_Ntrue.set_index('genes')

DESeq2_Ntrue.to_csv('DESeq2_Ntrue.csv')


DESeq2_Ntrue

           #R3  #R6  #R12  #R20
genes
15S_rRNA    23   20    15     7
21S_rRNA    25   21    12    10
HRA1         0   17    26    28
ICR1         0    0     0     0
LSR1         3    6     0     0
...        ...  ...   ...   ...
tY(GUA)J2    0    0     0     0
tY(GUA)M1    0    0     0     0
tY(GUA)M2    0    0     0     0
tY(GUA)O     0    0     0     0
tY(GUA)Q     0    0     0     0

[7126 rows x 4 columns]